app:
  image: golang:1.5.0
  command: ["go", "build"]
  working_dir: '/go/src/github.com/caiguanhao/wechat-notify'
  environment:
    - APPID
    - SECRET
  volumes:
    - '.:/go/src/github.com/caiguanhao/wechat-notify'
